/** Starter content shared by the browser app and the Node seed script. */

export const SEED = {
  users: [
    {
      id: 'nova',
      username: 'nova',
      displayName: 'Nova Reyes',
      bio: 'Speedrunner. Writes the story-mission guides nobody else wants to.',
      role: 'Contributor',
      joinedAt: '2025-11-02',
      location: 'Leeds, UK'
    },
    {
      id: 'mapmaker',
      username: 'mapmaker',
      displayName: 'Ari Kovac',
      bio: 'Cartographer for hire. Collectible routes and 100% checklists.',
      role: 'Moderator',
      joinedAt: '2025-09-14',
      location: 'Zagreb, HR'
    },
    {
      id: 'sable',
      username: 'sable',
      displayName: 'Sable',
      bio: 'Combat encounters, frame data and hard-mode strategies.',
      role: 'Contributor',
      joinedAt: '2026-01-20',
      location: 'Toronto, CA'
    },
    {
      id: 'pixelpush',
      username: 'pixelpush',
      displayName: 'Dana P.',
      bio: 'PC performance tuning and graphics settings comparisons.',
      role: 'Member',
      joinedAt: '2026-03-08',
      location: 'Austin, US'
    },
    {
      id: 'admin',
      username: 'admin',
      displayName: 'Companion for GTA6 Staff',
      bio: 'Official account. Announcements and rule changes.',
      role: 'Admin',
      joinedAt: '2025-08-01',
      location: 'Everywhere'
    }
  ],
  walkthroughs: [
    {
      id: 'gtao-event-drift-transform',
      title: 'GTA Online Event Week: Drift and Transform Races',
      game: 'GTA Online',
      category: 'Races',
      duration: 45,
      author: 'admin',
      likes: 0,
      approved: true,
      updatedAt: '2026-08-27',
      cover: '🏁',
      summary: 'Make the most of the 27 August to 2 September Drift and Transform event, including the three-race GTA$100,000 challenge.',
      tags: ['GTA Online', 'event week', 'races', 'weekly challenge'],
      steps: [
        'Complete three Drift Races to earn the GTA$100,000 weekly challenge reward. Winning is not required.',
        'Use the 6x GTA$ and RP window on selected Drift and Transform Races from 28 to 30 August.',
        'Use Random Transform Races for 3x GTA$ and RP, or Drift Races for 2x GTA$, RP, and LS Car Meet Rep.',
        'Complete a Drift Race in an Ubermacht Cypher to unlock the Glitch Camo Drift Livery; delivery can take up to 72 hours.',
        'Switch to Auto Shop Robbery Contracts when you want structured missions with 2x GTA$, RP, and LS Car Meet Rep.'
      ]
    },
    {
      id: 'gtao-drift-guide',
      title: 'Drift Guide: Tuning, Technique, and Race Tips',
      game: 'GTA Online',
      category: 'Cars',
      duration: 30,
      author: 'sable',
      likes: 0,
      approved: true,
      updatedAt: '2026-08-27',
      cover: '💨',
      summary: 'Learn controlled oversteer, avoid common mistakes, and prepare an eligible car for Drift Races.',
      tags: ['GTA Online', 'drifting', 'LS Car Meet', 'races'],
      steps: [
        'Enter a corner with enough speed, turn in, then tap the handbrake or use throttle to break rear-wheel traction.',
        'Counter-steer into the slide and make small throttle adjustments to hold the drift.',
        'Avoid entering too fast, holding the handbrake too long, or trying to drift every corner.',
        'Test Drift Tuning in a low-pressure session before racing competitively.',
        'The Annis Elegy Retro Custom, Invetero Coquette, and Vapid Dominator GTT are eligible for Drift Tuning in this event.',
        'Complete three Drift Races to finish the weekly challenge.'
      ]
    },
    {
      id: 'gtao-auto-shop-contracts',
      title: 'Auto Shop Robbery Contracts: Solo Setup Guide',
      game: 'GTA Online',
      category: 'Missions',
      duration: 60,
      author: 'nova',
      likes: 0,
      approved: true,
      updatedAt: '2026-08-27',
      cover: '🔧',
      summary: 'A practical route for running Auto Shop Robbery Contracts during the 2x reward event week.',
      tags: ['GTA Online', 'Auto Shop', 'money', 'solo'],
      steps: [
        'Buy an Auto Shop property and enter it to access the planning board.',
        'Choose an available Robbery Contract and complete its preparation missions.',
        'Stock up on armor and snacks before starting the finale.',
        'Use a fast armoured vehicle between objectives and take safe routes when playing solo.',
        'Finish the finale to collect the 2x GTA$, RP, and LS Car Meet Rep payout.',
        'Rotate into Drift or Random Transform Races when new contracts are on cooldown.'
      ]
    },
    {
      id: 'gtao-vehicle-spotlight',
      title: 'Vehicle Spotlight: Sultan Classic and Veto Classic',
      game: 'GTA Online',
      category: 'Cars',
      duration: 15,
      author: 'mapmaker',
      likes: 0,
      approved: true,
      updatedAt: '2026-08-27',
      cover: '🚘',
      summary: 'Track the weekly Podium Vehicle, Prize Ride requirement, and the 30 percent discount watchlist.',
      tags: ['GTA Online', 'vehicles', 'Lucky Wheel', 'Prize Ride'],
      steps: [
        'Visit The Diamond Casino and spin the Lucky Wheel once per real-world day for a chance at the Karin Sultan Classic.',
        'Place in the top five of the LS Car Meet Series for four days in a row to unlock the Dinka Veto Classic Prize Ride.',
        'Track each of the four top-five finishes and claim the Prize Ride after the requirement is complete.',
        'Check the weekly discounts before buying the Cheval Taipan, Vapid Flash GT, Invetero Coquette D5, Annis ZR350, or other watchlist vehicles.',
        'Remember that weekly vehicles and discounts rotate after the event ends.'
      ]
    },
    {
      id: 'gtao-weekend-racing-grind',
      title: 'Weekend Racing Grind: 6x GTA$ and RP Route',
      game: 'GTA Online',
      category: 'Money',
      duration: 50,
      author: 'pixelpush',
      likes: 0,
      approved: true,
      updatedAt: '2026-08-27',
      cover: '💰',
      summary: 'A flexible weekend route for the 28 to 30 August six-times reward window and the rest of Drift Week.',
      tags: ['GTA Online', 'money', 'races', 'grind'],
      steps: [
        'Start with a Drift Race and repeat until the three-race weekly challenge is complete.',
        'Claim the GTA$100,000 challenge reward after participating in three Drift Races.',
        'Move into selected Drift and Transform Races during the 6x reward window.',
        'Rotate into Random Transform Races for 3x GTA$ and RP when you want a change of pace.',
        'Use Auto Shop Robbery Contracts for structured 2x-reward missions between race queues.',
        'Track earnings, race wins, and LS Car Meet Reputation so you can compare your route next week.'
      ]
    },
    {
      id: 'wt-1',
      title: 'Prologue: Getting Out of Town',
      game: 'GTA 6',
      category: 'Missions',
      duration: 25,
      author: 'nova',
      likes: 12,
      approved: true,
      updatedAt: '2026-08-12',
      summary: 'Complete the opening heist and escape the county line without losing wanted stars.',
      tags: ['story', 'beginner'],
      steps: [
        'Follow the on-screen prompts to reach the getaway vehicle.',
        'Stick to back roads to avoid the first police checkpoint.',
        'Swap vehicles at the barn to drop your wanted level.',
        'Drive to the safehouse and stash the loot.'
      ]
    },
    {
      id: 'wt-2',
      title: 'All Collectible Locations',
      game: 'GTA 6',
      category: 'Collectibles',
      duration: 180,
      author: 'mapmaker',
      likes: 26,
      approved: true,
      updatedAt: '2026-08-20',
      summary: 'Region-by-region route for every hidden collectible with the fastest travel order.',
      tags: ['collectibles', '100%'],
      steps: [
        'Unlock fast travel by finishing the second story chapter.',
        'Sweep the coastal region from south to north.',
        'Clear the inland swamp at night for easier spotting.',
        'Finish with the city rooftops using a helicopter.'
      ]
    },
    {
      id: 'wt-3',
      title: 'Hard Mode Boss Strategy',
      game: 'GTA 6',
      category: 'Missions',
      duration: 45,
      author: 'sable',
      likes: 19,
      approved: true,
      updatedAt: '2026-08-25',
      summary: 'Loadout, cover positions and timing windows for the final confrontation.',
      tags: ['combat', 'endgame'],
      steps: [
        'Bring armor-piercing rounds and at least three medkits.',
        'Use the left-side cover to bait the first attack pattern.',
        'Break line of sight when the shield phase begins.',
        'Focus damage during the reload window after each volley.'
      ]
    },
    {
      id: 'wt-4',
      title: 'Fast Money in the First 5 Hours',
      game: 'GTA 6',
      category: 'Money',
      duration: 60,
      author: 'nova',
      likes: 9,
      approved: true,
      updatedAt: '2026-08-18',
      summary: 'Repeatable early-game income loop that requires no upfront investment.',
      tags: ['economy', 'beginner'],
      steps: [
        'Complete the courier side jobs near the docks.',
        'Sell recovered vehicles at the west chop shop.',
        'Reinvest in a garage slot to double payout capacity.'
      ]
    }
  ],
  threads: [
    {
      id: 'gtao-th-drift-build',
      title: 'Show your drift build',
      category: 'GTA Online',
      author: 'admin',
      likes: 0,
      createdAt: '2026-08-27',
      body: 'Post your vehicle, upgrades, controller settings, and best tips for holding a long drift during Drift Week.',
      replies: []
    },
    {
      id: 'gtao-th-weekly-challenge',
      title: 'Best way to finish the weekly challenge?',
      category: 'GTA Online',
      author: 'admin',
      likes: 0,
      createdAt: '2026-08-27',
      body: 'Which Drift Races feel fastest and easiest for completing three races? Winning is not required, so share a reliable route for newer players.',
      replies: []
    },
    {
      id: 'gtao-th-transform-strategy',
      title: 'Transform Race strategy',
      category: 'GTA Online',
      author: 'admin',
      likes: 0,
      createdAt: '2026-08-27',
      body: 'Do you prioritise clean checkpoint lines, aggressive overtakes, or risky shortcuts when the vehicle class changes?',
      replies: []
    },
    {
      id: 'gtao-th-contract-crew',
      title: 'Auto Shop contract crew finder',
      category: 'GTA Online',
      author: 'admin',
      likes: 0,
      createdAt: '2026-08-27',
      body: 'Find players for Auto Shop preparation missions and contract finales. Include your platform, timezone, and preferred playstyle.',
      replies: []
    },
    {
      id: 'gtao-th-vehicle-deals',
      title: 'Vehicle deal verdicts',
      category: 'GTA Online',
      author: 'admin',
      likes: 0,
      createdAt: '2026-08-27',
      body: 'Which discounted vehicle is worth buying this week, and which should players skip? Explain the value for new and returning players.',
      replies: []
    },
    {
      id: 'th-1',
      title: 'Best settings for 60fps on mid-range hardware?',
      category: 'Tech',
      author: 'pixelpush',
      likes: 8,
      createdAt: '2026-08-24',
      body: 'Shadows and volumetric fog seem to be the biggest cost. What are you all running?',
      replies: [
        { id: 'r-1', author: 'sable', createdAt: '2026-08-24', body: 'Drop volumetrics to medium first, it is worth ~12fps.' },
        { id: 'r-2', author: 'nova', createdAt: '2026-08-25', body: 'Also cap the framerate, the frametimes get much smoother.' }
      ]
    },
    {
      id: 'th-2',
      title: 'Missable trophies list — help me verify',
      category: 'Guides',
      author: 'mapmaker',
      likes: 14,
      createdAt: '2026-08-21',
      body: 'I have found four so far. Adding them to the collectibles walkthrough once confirmed.',
      replies: [
        { id: 'r-3', author: 'pixelpush', createdAt: '2026-08-22', body: 'The chapter 3 photo one is definitely missable.' }
      ]
    },
    {
      id: 'th-3',
      title: 'Introduce yourself here',
      category: 'General',
      author: 'admin',
      likes: 3,
      createdAt: '2026-08-01',
      body: 'New here? Say hello and tell us what you are playing.',
      replies: []
    }
  ],
  pendingWalkthroughs: [
    {
      id: 'pwt-seed-1',
      title: 'Secret Vehicle Spawns in Vice Port',
      game: 'GTA 6',
      category: 'Cars',
      duration: 15,
      author: 'pixelpush',
      authorUid: 'pixelpush',
      likes: 0,
      updatedAt: '2026-08-20',
      createdAt: '2026-08-20',
      summary: 'Detailed coordinate points and times for rare muscle cars in the industrial shipping docks.',
      tags: ['vehicles', 'secrets', 'vice-port'],
      steps: [
        { title: 'Head to the East Cranes', content: 'Arrive at the shipping yard between 02:00 and 04:00 in-game time.' },
        { title: 'Check Warehouse 4B', content: 'The shutter door has a small opening on the south side where the vehicle spawns.' }
      ]
    }
  ],
  news: [
    {
      id: 'gta6-official-release-date',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'Grand Theft Auto VI launches 19 November 2026',
      cover: '🌴',
      source: 'Official Rockstar Games',
      summary: 'Rockstar Games lists Grand Theft Auto VI for release on 19 November 2026. The game takes players to Vice City and the wider state of Leonida.',
      body: 'Grand Theft Auto VI is scheduled to launch on **19 November 2026**.\n\nRockstar’s official GTA VI hub describes a story set in Vice City and the wider fictional state of Leonida. Jason and Lucia are pulled into a criminal conspiracy after an easy score goes wrong, leaving the pair dependent on one another to survive.\n\n### What is confirmed\n\n- Grand Theft Auto VI is set in Vice City and the state of Leonida\n- Jason Duval and Lucia Caminos are central characters\n- The story begins after an easy score goes wrong\n- The game launches on 19 November 2026\n- Rockstar has released official trailers, screenshots, artwork, character profiles, and an Extended Look feature',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-official-extended-look',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'GTA VI: An Extended Look is now playing',
      cover: '📰',
      source: 'Official Rockstar Games',
      summary: 'Rockstar has released Grand Theft Auto VI: An Extended Look. Watch the official feature, then explore the trailer archive, screenshots, characters, and Leonida location pages.',
      body: 'Rockstar Games has released **Grand Theft Auto VI: An Extended Look**.\n\nThe official GTA VI site now brings together the Extended Look, trailers, downloadable media, screenshots, artwork, character profiles, and Leonida location pages. It is a useful starting point for players who want to separate confirmed GTA VI information from community theories and unverified reports.\n\n### Explore next\n\n- Watch the Extended Look\n- Meet Jason, Lucia, and the supporting cast\n- Explore the official Leonida location pages\n- Browse official screenshots and artwork',
      publishedAt: '2026-08-27',
      createdAt: '2026-08-27',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-official-jason-profile',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'Meet Jason Duval',
      cover: '🎯',
      source: 'Official Rockstar Games',
      summary: 'Jason wants an easy life, but his past keeps pulling him deeper into trouble.',
      body: 'Jason Duval grew up around grifters and crooks. After a stint in the Army, he ended up working for local drug runners in the Leonida Keys.\n\nJason wants a different life, but meeting Lucia could either become his way out or pull him into something even more dangerous. Rockstar presents him as a character caught between familiar criminal work and the possibility of a new future.\n\n### Official profile highlights\n\n- Jason has a troubled past\n- He previously served in the Army\n- He worked for local drug runners in the Keys\n- He is closely connected to Lucia\n- His story is tied to the criminal underworld of Leonida',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-official-lucia-profile',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'Meet Lucia Caminos',
      cover: '🎯',
      source: 'Official Rockstar Games',
      summary: 'Fresh out of prison, Lucia is determined to take control of her future.',
      body: 'Lucia Caminos learned to fight from an early age. Fighting for her family landed her in Leonida Penitentiary, but after getting out, she is focused on making smarter moves.\n\nLucia wants the good life her mother dreamed of during their earlier days in Liberty City. Instead of waiting for that life to happen, she is prepared to create it herself — whatever the cost.\n\n### Official profile highlights\n\n- Lucia fought to protect her family\n- She spent time in Leonida Penitentiary\n- She has a connection to Liberty City through her family history\n- She is determined to improve her circumstances\n- Her relationship with Jason is central to the story',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-official-people-leonida',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'The people of Leonida',
      cover: '📰',
      source: 'Official Rockstar Games',
      summary: 'GTA VI’s official character pages introduce the hustlers, criminals, musicians, and operators around Jason and Lucia.',
      body: 'Leonida is home to characters chasing money, status, survival, or a way out.\n\n### Confirmed characters\n\n- **Cal Hampton** — Jason’s friend and Brian’s associate, who spends his time following Coast Guard communications and internet conspiracies\n- **Boobie Ike** — A Vice City figure with business interests in real estate, a strip club, and a recording studio\n- **Dre’Quan Priest** — An aspiring music mogul connected to Only Raw Records\n- **Real Dimez** — rap duo with a social-media presence and a deal with Only Raw Records\n- **Raul Bautista** — A seasoned bank robber who seeks people willing to take major risks\n- **Brian Heder** — A longtime Keys drug runner who operates through his boat yard',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-location-vice-city',
      category: 'Official',
      sourceType: 'Official Rockstar Games',
      title: 'Return to Vice City — and explore beyond it',
      cover: '🗺️',
      source: 'Official Rockstar Games',
      summary: 'GTA VI brings players back to Vice City, but the setting reaches beyond the neon skyline into the wider state of Leonida.',
      body: 'GTA VI takes place in Leonida, a fictional state that includes the famous neon-soaked streets of Vice City and several surrounding regions.\n\n### Officially named locations\n\n- **Vice City** — The major city at the centre of GTA VI’s setting\n- **Leonida Keys** — A coastal island region\n- **Port Gellhorn** — A named Leonida destination\n- **Ambrosia** — A named Leonida destination\n- **Grassrivers** — A named Leonida destination\n- **Mount Kalaga National Park** — A named national-park region',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-gameplay-footage-analysis',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'Gameplay hub: What Rockstar footage tells us so far',
      cover: '🎮',
      source: 'Official footage analysis',
      summary: 'A spoiler-light guide to exploring official GTA VI footage without confusing observations with confirmed features.',
      body: 'GTA VI’s official footage focuses on the relationship between Jason and Lucia, the contrast between Vice City and the wider state of Leonida, and a criminal story that escalates after a job goes wrong.\n\nThis gameplay hub is designed to help players revisit official material carefully.\n\n### Confirmed story framework\n\n- The game is set in Vice City and the wider state of Leonida\n- Jason and Lucia are at the centre of the story\n- An easy score goes wrong\n- The pair become involved in a larger criminal conspiracy\n- Rockstar has released official video, screenshots, and character/location pages\n\n### Keep expectations realistic\n\nDo not treat fan frame analysis as confirmation of missions, weapons, vehicles, interiors, side activities, online features, or map scale. Add those only after Rockstar explicitly confirms them or after launch.',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'nova',
      authorUid: 'nova'
    },
    {
      id: 'gta6-gameplay-jason-lucia',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'Jason and Lucia: A partnership under pressure',
      cover: '🎮',
      source: 'Official footage analysis',
      summary: 'Official GTA VI material centres Jason and Lucia as a criminal partnership. Their relationship sits at the heart of a story that begins when an easy score goes wrong.',
      body: 'Jason and Lucia are not simply two separate character biographies. Rockstar’s official premise presents them as partners forced to rely on each other when a simple job goes wrong.\n\nJason has experience in the criminal world of the Leonida Keys. Lucia has just left prison and is focused on changing her position in life. Together, they become tied to the darker side of Leonida.\n\n### Discussion question\n\nDo you expect the story to focus more on trust between Jason and Lucia, or on the pressure created by the people around them?',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'nova',
      authorUid: 'nova'
    },
    {
      id: 'gta6-gameplay-world-guide',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'Vice City is only one part of Leonida',
      cover: '🗺️',
      source: 'Official footage analysis',
      summary: 'The official location reveals show a world with city streets, coastal areas, national parkland, and other distinct regions.',
      body: 'Vice City remains one of GTA’s most recognisable settings, but Rockstar’s official media makes it clear that GTA VI is not limited to the city.\n\nThe wider state of Leonida includes locations such as the Leonida Keys, Port Gellhorn, Ambrosia, Grassrivers, and Mount Kalaga National Park. That variety gives the game a broader setting for missions, travel, exploration, and story encounters.\n\n### Location tracker\n\n- [ ] Visit Vice City\n- [ ] Visit the Leonida Keys\n- [ ] Visit Port Gellhorn\n- [ ] Visit Ambrosia\n- [ ] Visit Grassrivers\n- [ ] Visit Mount Kalaga National Park',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'mapmaker',
      authorUid: 'mapmaker'
    },
    {
      id: 'gta6-gameplay-jason-world',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'From the Keys to Vice City: Jason’s world',
      cover: '🌴',
      source: 'Official footage analysis',
      summary: 'Jason’s backstory connects him to the coastal criminal underworld of the Leonida Keys.',
      body: 'Before the events of GTA VI, Jason spent time in the Leonida Keys working for local drug runners. His connection to the area gives players an early link between the neon city environment of Vice City and the coastal regions beyond it.\n\nBrian Heder, a longtime smuggler operating from a boat yard, is one of the people connected to Jason’s past.\n\n### Things to watch in official footage\n\n- Coastal roads and waterways\n- Boat yards and marina environments\n- Keyes nightlife and small-town spaces\n- Jason’s interactions with figures from his past\n- The contrast between Jason’s old life and his plans with Lucia',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'nova',
      authorUid: 'nova'
    },
    {
      id: 'gta6-gameplay-criminal-world',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'A spoiler-free guide to GTA VI’s criminal world',
      cover: '📰',
      source: 'Official footage analysis',
      summary: 'Meet the people positioned around Leonida’s music, nightlife, smuggling, and robbery scenes.',
      body: 'Rockstar’s character profiles point toward several overlapping worlds in Leonida:\n\n- **Smuggling:** Brian Heder’s long history in the Keys\n- **Street-level crime:** Jason’s past around local drug runners\n- **High-risk robberies:** Raul Bautista’s search for capable people\n- **Nightlife and business:** Boobie Ike’s Vice City empire\n- **Music and celebrity:** Dre’Quan Priest and Real Dimez at Only Raw Records\n\nThe app should treat these as story context, not as a confirmed mission list.',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-gameplay-footage-checklist',
      category: 'Gameplay',
      sourceType: 'Official footage analysis',
      title: 'Footage analysis checklist',
      cover: '📰',
      source: 'Official footage analysis',
      summary: 'Use this checklist before sharing an apparent GTA VI discovery.',
      body: 'When players discover an interesting moment in a trailer, screenshot, or Extended Look, use this checklist:\n\n- [ ] Is this shown in official Rockstar material?\n- [ ] Is it clearly visible, rather than a blurry background detail?\n- [ ] Has Rockstar explicitly named or described it?\n- [ ] Is it a visual observation or a confirmed game mechanic?\n- [ ] Could it be a cinematic scene rather than normal gameplay?\n- [ ] Does another official source support the conclusion?\n- [ ] Has the post been labelled Official, Footage Analysis, or Rumour?',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-rumour-map-size',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'Rumour Watch: How large will Leonida be?',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'Fans are comparing official screenshots, trailers, and location reveals to predict the scale of GTA VI\'s map. Rockstar has not published an official map size.',
      body: 'Fans are comparing official screenshots, trailers, and location reveals to predict the scale of GTA VI\'s map. Rockstar has not published an official map size.\n\nRockstar has confirmed several named locations across Leonida, including Vice City, the Leonida Keys, Port Gellhorn, Ambrosia, Grassrivers, and Mount Kalaga National Park.\n\nThe unconfirmed part is how those locations will connect in actual play.\n\n### Community questions\n\n- Will water travel play a major role between coastal locations?\n- Will rural roads connect every named region?\n- Could some areas unlock later in the story?\n- Which region looks most likely to become a fan favourite?',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-rumour-wildcard-character',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'Theory: Which side character could become the biggest wildcard?',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'Raul Bautista, Brian Heder, Boobie Ike, and Cal Hampton all have fans debating who could create the most trouble for Jason and Lucia.',
      body: 'Rockstar has given each supporting character a distinct background, but it has not explained their full role in the plot.\n\n### Pick one\n\n- Raul Bautista — the experienced bank robber\n- Brian Heder — the Keys smuggler and Jason’s landlord\n- Boobie Ike — the Vice City businessman\n- Cal Hampton — Jason’s conspiracy-focused friend\n- Dre’Quan Priest — the rising music figure\n- Real Dimez — the viral rap duo',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-rumour-online-mode',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'Rumour Watch: Will GTA VI receive an online mode?',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'GTA Online’s success has led to major fan speculation about a future online mode, but Rockstar has not announced GTA VI multiplayer details.',
      body: 'Fans expect Rockstar to discuss an online future eventually, but expectations should not be treated as news.\n\nUntil Rockstar makes an announcement, the app should list all claims about multiplayer, roleplay support, GTA Online migration, cross-platform play, servers, jobs, heists, or progression systems as unconfirmed.\n\n### Community question\n\nWhat would you most want from a future GTA VI online experience?\n\n- Better cooperative missions\n- More player-owned businesses\n- Improved crew features\n- More social spaces\n- Better anti-cheat tools\n- Cross-platform play\n- Regular community events',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-rumour-cal-hampton',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'Theory: Is Cal Hampton hiding more than he knows?',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'Cal spends his time listening to Coast Guard communications and following internet conspiracies. Fans are debating whether his paranoia could become important.',
      body: 'Cal Hampton is described as Jason’s friend and a fellow associate of Brian. His official profile portrays him as someone who follows strange patterns, private browsing, and Coast Guard communications.\n\nThat does not confirm he is part of a major plot twist — but it gives the community plenty to discuss.',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: true,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-rumour-photo-predictions',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'Prediction: Which Leonida location will dominate the first screenshots after launch?',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'GTA fans are already choosing between city nightlife, beach sunsets, swamps, small-town spaces, and mountain scenery.',
      body: '### Community Poll Options\n\n- Vice City at night\n- The Leonida Keys\n- Port Gellhorn\n- Ambrosia\n- Grassrivers\n- Mount Kalaga National Park',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-rumour-false-claims',
      category: 'Rumour',
      sourceType: 'Community speculation',
      title: 'False claims to avoid before launch',
      cover: '⚡',
      source: 'Community speculation',
      summary: 'Keep rumours useful by separating predictions from fake “leaks.”',
      body: '### Do not treat these as confirmed unless Rockstar announces them\n\n- Exact map dimensions\n- Full mission count\n- Full vehicle list\n- Full weapon list\n- Online mode details\n- Cross-platform support\n- PC release date\n- System requirements\n- DLC roadmap\n- Microtransaction details\n- Trophy or achievement lists\n- A complete radio soundtrack\n- A full list of explorable interiors',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-trailer-extended-look',
      category: 'Trailer',
      sourceType: 'Official Rockstar Games',
      title: 'Grand Theft Auto VI: An Extended Look',
      cover: '🌴',
      source: 'Official Rockstar Games',
      summary: 'Rockstar’s Extended Look is available through the official GTA VI site.',
      body: '### Video Details\n\n- Title: Grand Theft Auto VI: An Extended Look\n- Category: Trailer\n- Type: Official Video\n- Official: Yes\n- Video Route: /trailers/extended-look',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-trailer-1',
      category: 'Trailer',
      sourceType: 'Official Rockstar Games',
      title: 'Trailer 1: The first return to Vice City',
      cover: '🎮',
      source: 'Official Rockstar Games',
      summary: 'Watch the first official GTA VI trailer and revisit the video that introduced Leonida, Vice City, and Lucia to the world.',
      body: 'The first official GTA VI trailer introduced the return to Vice City and gave fans their first major look at Leonida.\n\n### Watch guide\n\n- Watch once with no pauses for the overall tone\n- Rewatch for background details\n- Explore the locations shown in the map hub\n- Read official character profiles afterward\n- Avoid treating every visual detail as confirmation of a gameplay feature',
      publishedAt: '2023-12-05',
      createdAt: '2023-12-05',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-trailer-2',
      category: 'Trailer',
      sourceType: 'Official Rockstar Games',
      title: 'GTA VI Trailer 2',
      cover: '🎮',
      source: 'Official Rockstar Games',
      summary: 'Continue the official GTA VI video archive with Trailer 2, then compare the footage with Rockstar’s character and Leonida pages.',
      body: 'Continue the official GTA VI video archive with Trailer 2, then compare the footage with Rockstar’s character and Leonida pages.',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-trailer-screenshots',
      category: 'Trailer',
      sourceType: 'Official Rockstar Games',
      title: 'Official screenshots and artwork',
      cover: '🗺️',
      source: 'Official Rockstar Games',
      summary: 'Rockstar’s GTA VI media section includes official videos, screenshots, downloadable artwork, and wallpapers.',
      body: '### Screenshot location collection\n\n- Vice City\n- Leonida Keys\n- Port Gellhorn\n- Ambrosia\n- Grassrivers\n- Mount Kalaga National Park',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-trailer-reaction',
      category: 'Trailer',
      sourceType: 'Community companion',
      title: 'Trailer reaction thread',
      cover: '📻',
      source: 'Community companion',
      summary: 'Share your favourite moment from an official GTA VI trailer or the Extended Look.',
      body: '### Thread rules\n\n- Use spoiler tags for detailed scene discussion\n- Include a timestamp when referencing a video moment\n- Mark theories as theories\n- Do not upload copyrighted trailer clips\n- Do not repost stolen or leaked development material\n- Keep discussion respectful',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    },
    {
      id: 'gta6-community-character-poll',
      category: 'Community',
      sourceType: 'Community poll',
      title: 'Poll: Which character are you most interested in?',
      cover: '📻',
      source: 'Community poll',
      summary: 'Jason and Lucia are at the heart of GTA VI, but Leonida has a wider cast of criminals, business figures, musicians, and outsiders.',
      body: '### Poll options\n\n- Jason Duval\n- Lucia Caminos\n- Cal Hampton\n- Boobie Ike\n- Dre’Quan Priest\n- Real Dimez\n- Raul Bautista\n- Brian Heder',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'nova',
      authorUid: 'nova'
    },
    {
      id: 'gta6-community-first-day-plan',
      category: 'Community',
      sourceType: 'Community discussion',
      title: 'Build your ideal first-day GTA VI plan',
      cover: '📻',
      source: 'Community discussion',
      summary: 'GTA VI is approaching. What will you do first when you enter Leonida?',
      body: '### Suggested answers\n\n- Follow the story with no distractions\n- Explore Vice City immediately\n- Drive to every named location\n- Search for Easter eggs\n- Take screenshots and use photo mode\n- Learn the vehicle handling\n- Complete side activities first\n- Avoid social media until finishing the story',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'mapmaker',
      authorUid: 'mapmaker'
    },
    {
      id: 'gta6-community-guide-request',
      category: 'Community',
      sourceType: 'Community requests',
      title: 'Community guide request board',
      cover: '📻',
      source: 'Community requests',
      summary: 'Tell the guide team what content you want ready for launch day.',
      body: '### Request categories\n\n- Beginner tips\n- First-hour checklist\n- Money guide\n- Vehicle guide\n- Weapon guide\n- Collectible tracker\n- Story walkthrough\n- 100 percent completion tracker\n- Trophy and achievement tracker\n- Best settings guide\n- Accessibility guide\n- Spoiler-free location guide',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'mapmaker',
      authorUid: 'mapmaker'
    },
    {
      id: 'gta6-community-favourite-location',
      category: 'Community',
      sourceType: 'Community poll',
      title: 'Poll: Which Leonida location are you exploring first?',
      cover: '🗺️',
      source: 'Community poll',
      summary: 'Vote for Vice City, the Leonida Keys, Port Gellhorn, Ambrosia, Grassrivers, or Mount Kalaga National Park.',
      body: '### Challenge format\n\n```text\nLocation:\nPhoto idea:\nTime of day:\nVehicle choice:\nCharacter choice:\nWhy this spot:\n```\n\n### Featured locations\n\n- Vice City\n- Leonida Keys\n- Port Gellhorn\n- Ambrosia\n- Grassrivers\n- Mount Kalaga National Park',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'mapmaker',
      authorUid: 'mapmaker'
    },
    {
      id: 'gta6-community-feature-reveal',
      category: 'Community',
      sourceType: 'Community poll',
      title: 'One feature you want Rockstar to explain next',
      cover: '📻',
      source: 'Community poll',
      summary: 'Rockstar has shared story, character, location, and video material. What should the next official reveal focus on?',
      body: '### Poll options\n\n- More story information\n- More character details\n- Open-world activities\n- Vehicles and travel\n- Weapons and combat\n- Exploration\n- Accessibility features\n- PC version information\n- Future online plans\n- Collector’s edition details',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'pixelpush',
      authorUid: 'pixelpush'
    },
    {
      id: 'gta6-community-crew-finder',
      category: 'Community',
      sourceType: 'Community',
      title: 'GTA VI launch-day crew finder',
      cover: '📻',
      source: 'Community',
      summary: 'Find people in your region to discuss GTA VI, share spoiler-safe progress, and prepare for any future official multiplayer announcement.',
      body: '### Profile fields\n\n```json\n{\n  "platform": "PlayStation 5 | Xbox Series X|S | Unknown",\n  "timezone": "NZST | AEST | PST | EST | GMT | Other",\n  "spoilerPreference": "No spoilers | Light spoilers | All spoilers allowed",\n  "playStyle": "Story | Exploration | Completionist | Screenshots | Community",\n  "availability": "Weekdays | Weekends | Evenings | Flexible",\n  "bio": ""\n}\n```',
      publishedAt: '2026-08-28',
      createdAt: '2026-08-28',
      isSpoiler: false,
      author: 'admin',
      authorUid: 'admin'
    }
  ]
};

export const CATEGORIES = ['General', 'Guides', 'Tech', 'News', 'GTA Online', 'Off-topic'];

export const TROPHIES = [
  { id: 't-01', title: 'Welcome to Vice City', description: 'Complete the opening mission.', category: 'Story', tier: 'Bronze' },
  { id: 't-02', title: 'No Loose Ends', description: 'Complete the main story.', category: 'Story', tier: 'Gold' },
  { id: 't-03', title: 'Smooth Operator', description: 'Complete a mission without raising your wanted level.', category: 'Story', tier: 'Bronze' },
  { id: 't-04', title: 'Sunset Boulevard', description: 'Visit every major district in the city.', category: 'Exploration', tier: 'Silver' },
  { id: 't-05', title: 'Off the Grid', description: 'Discover 25 hidden locations.', category: 'Exploration', tier: 'Silver' },
  { id: 't-06', title: 'Four Wheels', description: 'Collect 10 unique vehicles.', category: 'Exploration', tier: 'Bronze' },
  { id: 't-07', title: 'Big Score', description: 'Earn $1,000,000 from side activities.', category: 'Side Activities', tier: 'Gold' },
  { id: 't-08', title: 'Night Shift', description: 'Finish a full night of taxi work.', category: 'Side Activities', tier: 'Bronze' },
  { id: 't-09', title: 'Local Legend', description: 'Reach maximum reputation with one crew.', category: 'Side Activities', tier: 'Silver' },
  { id: 't-10', title: 'Sharp Eye', description: 'Find 10 hidden photo spots.', category: 'Collectibles', tier: 'Bronze' },
  { id: 't-11', title: 'Full Deck', description: 'Collect every special playing card.', category: 'Collectibles', tier: 'Silver' },
  { id: 't-12', title: 'Treasure Hunter', description: 'Complete a full treasure map.', category: 'Collectibles', tier: 'Bronze' }
];
